
future: false

author: "Nick Stanley"

highlighter: rouge
plugins:
  - jekyll-sitemap

collections:
  slides:
    output: true
    permalink: slide/:title/
  slides_test:
    output: true
    permalink: slide/:title/
  notes:
    output: true
    permalink: note/:title/
